### ISSUE TITLE
Proposta logo QGIS ITALIA

### ISSUE THREAD

**Issue by slarosa** [pigreco/logo_QGIS_3ITA#2]
![qgis_ita_logo_minor_size](https://user-images.githubusercontent.com/1374682/31334346-3d933bc4-acee-11e7-82bc-e468843f66e9.png)

**Comment by pigreco** [comment]
@slarosa 
mi piace un sacco.

**Comment by pigreco** [comment]
ecco le simulazioni
![image](https://user-images.githubusercontent.com/7631137/31333740-932a3202-aceb-11e7-8190-4d79993223f7.png)

![image](https://user-images.githubusercontent.com/7631137/31333757-9f296122-aceb-11e7-8f8b-028c5cf7b534.png)

**Comment by slarosa** [comment]
l'ho rifatto utilizzando il pantone della bandiera Italiana (https://en.wikipedia.org/wiki/Flag_of_Italy)
e mantenendo la stessa struttura di quello originale.

![qgis_ita_logo](https://user-images.githubusercontent.com/1374682/31334040-b40ae13c-acec-11e7-82cd-0876494bb758.png)

...ed ho aggiornato il primo messaggio :-)

**Comment by slarosa** [comment]
qui il logo in SVG: https://www.dropbox.com/s/zhh7n2sw8qqgn72/qgis-logo_ita.svg?dl=0

**Comment by pigreco** [comment]
@slarosa 
svg aggiunto qui: https://github.com/pigreco/logo_QGIS_3ITA/blob/master/proposte/slarosa/qgis-logo3_ITA.svg

**Comment by ghtmtt** [comment]
se devo essere sincero, a me il logo attuale piace. Però devo anche ammettere che questo logo e l'idea di @slarosa è davvero bella. Quindi +1 per quest'ultimo :)

**Comment by skampus** [comment]
Continuo a preferire l'attuale

**Comment by pigreco** [comment]
@slarosa @ghtmtt @skampus @aborruso 
la mia idea è quella di creare un repo con tutte le possibili configurazioni del logo e condividerlo tramite il plugin [Resource sharing](https://pigrecoinfinito.wordpress.com/2017/10/08/qgis-condividere-risorse-plugin-resource-sharing/) - cosi tutti gli utenti italiani possono usare il logo nei loro lavori.
ecco un esempio:
![image](https://user-images.githubusercontent.com/7631137/31339654-deac850a-ad03-11e7-88ed-b5cb34c3c009.png)

come gruppo dovremmo dare qualche servizietto, no?

quello attuale NON si presta alle varie configurazioni:
![image](https://user-images.githubusercontent.com/7631137/31339955-cf450956-ad04-11e7-8f50-5696742873a8.png)

**Comment by slarosa** [comment]
_Oh Ragassi… Siam mica qui a mettere i rayban ai girasoli, ragassi!!!_

Concordo con quanto detto da @pigreco, il logo deve avere delle caratteristiche che in linea di massima sono quelle che sono state già menzionate in questa discussione. Mi rendo conto che non è semplice decidere, ma se la modifica comporta solo l'aggiornamento della pagina FB, per quanto mi riguarda possiamo procedere alla sostituzione del logo attuale con uno di quelli già proposti o con altre proposte semmai arriveranno. Però temo sia necessario attivare un sondaggio!

Cosa diversa è se il logo deve essere condiviso attraverso il plugin Resource sharing, a quel punto meglio condividere qualcosa che sia conforme a quanto detto da @pigreco.

e comunque vada, grazie @pigreco per aver attivato questo processo!

**Comment by skampus** [comment]
Scusate se faccio il democristiano, ma dato che lo condividiamo attraverso
il repo di Totò non possiamo sceglierne due o tre che "riconosciamo" e che
possiamo usare nelle occasioni ufficiali, disponibili come png,  svg e
tiff?

Il 10/Ott/2017 16:53, "Salvatore Larosa" <notifications@github.com> ha
scritto:

**Comment by aborruso** [comment]
Aggiungo anche la mia proposta 🥇 

![image](https://user-images.githubusercontent.com/30607/31394806-88118902-addf-11e7-85fc-5171a122db23.png)

In svg https://github.com/pigreco/logo_QGIS_3ITA/blob/master/proposte/aborruso/qgis-logo3_ITA.svg

**Comment by pigreco** [comment]
@aborruso sai che ti voglio un mondo di bene, mi piace pure il tuo logo ma se dovessimo condividerlo e creare le varie configurazioni (original, green, blak e white) la tua idea mi sembra di difficile realizzazione.
ma è solo un mio parere.

@slarosa concordo per il sondaggio; dove farlo e come?

**Comment by ghtmtt** [comment]
un semplice doodle? però aspettiamo di avere tutte le proposte? altrimenti mettiamo su un sondaggio, si vota, altre proposte, casini ecc...

**Comment by aborruso** [comment]
@pigreco  mi faceva solo piacere mostarlo. Scusate l'off-topic

**Comment by slarosa** [comment]
@pigreco wrote:
> @slarosa concordo per il sondaggio; dove farlo e come?

Un semplice doodle dovrebbe essere sufficiente, rimarcando quanto già detto da @ghtmtt.

**Comment by pigreco** [comment]
@ghtmtt @slarosa 
che significa fare un semplice doodle?

@aborruso non sei mai OT, sono io che esagero sempre!!! scusate!!!

**Comment by pigreco** [comment]
@aborruso @skampus @ghtmtt @slarosa 
permettetemi un piccolo riassunto:
le proposto fino ad ora sono tre e sono [qui](https://github.com/pigreco/logo_QGIS_3ITA/tree/master/proposte) più la proposta di @skampus di lasciare tutto per come è.
**Domanda:** in questa issue siamo solo in 5, come e dove fare un sondaggio o aspettare nuove proposte? chi può fare nuove proposte? nella ML del gruppo NON risponde nessuno!!!

**Comment by slarosa** [comment]
> Domanda: in questa issue siamo solo in 5, come e dove fare un sondaggio o aspettare nuove proposte? chi può fare nuove proposte? nella ML del gruppo NON risponde nessuno!!!

Io credo che possiamo deciderlo anche in pochi (gruppo ML), altrimenti andiamo incontro a delle lungaggini inutili. Il sondaggio proposto in #4 va bene secondo me. Ma aspettiamo altri pareri.

**Comment by aborruso** [comment]
Ragazzi io sono un po' silente, perché non conosco bene il contesto.
Se ho capito bene si vuole fare un sondaggio per proporre un nuovo logo per sito e gruppo facebook.

Come vengono prese le decisioni per il sito? Nella mailing list non pubblica di QGIS Italia?

Come vengono prese nel gruppo fb?

Il gruppo fb è un'estensione social del gruppo che gestisce il sito, o è  come immagino qualcosa di ancora più informale e orizzontale?

Io in questo sondaggio vedo la complicazione di definizione di contesto. 

Se non ho capito nulla, ignoratemi

**Comment by skampus** [comment]
occhio che mi sembra di capire dagli indirizzi che cis tiamo rispondendo
via github, sbaglio?

Il giorno 12 ottobre 2017 11:19, Salvatore Larosa <notifications@github.com>
ha scritto:

**Comment by pigreco** [comment]
Perdonatemi, ma @aborruso  ha ragione, mi sono spiegato male o quanto meno non ho creato le giuste condizioni per evidenziare la mia idea, nata per caso e mi è sfuggita di mano.

Sintetizzando al massimo:

La mia idea è di creare un set di loghi, a varie dimensioni e colori come [qui](https://www.qgis.org/en/site/getinvolved/styleguide.html) da condividere tramite il plugin Resource sharing.
I loghi su FB o il sito saranno solo la conseguenza della scelta che faremo.

saluti

**Comment by pigreco** [comment]
Aggiungo:
il logo [attuale](https://github.com/pigreco/logo_QGIS_3ITA/blob/master/MARCHIO_ATTUALE.png) è stato creato in fretta senza sondaggi e senza nessun problema; abbiamo deciso solo io, Nino Formica,  Matteo @ghtmtt e Paolo nel gruppo chiuso!!!
Io non ho problemi ad estenderla a tutti!!! Ma per cortesia decidiamo quanto prima!!!

**Comment by pigreco** [comment]
@aborruso @slarosa @ghtmtt @skampus 
per favore leggete [Wiki](https://github.com/pigreco/logo_QGIS_3ITA/wiki) dove ho scritto con maggiore dettaglio la mia idea iniziale!!!

**Comment by aborruso** [comment]
@pigreco grazie, ho capito. È una buona idea e io voto "La Rosa". Il mio è sbagliato, ma non avevo capito gli obiettivi :)

Ma prima di scegliere vuoi proporre nei vari spazi web di inviare altre idee qui? Tenere aperta la cosa per due settimane?

**Comment by skampus** [comment]
ho riletto bene tutto in fila l'evolversi dei ragionamenti e rispetto
all'esigenza primaria di creare set  di marchi da rendere anche in b/n
secondo le specifiche di stile di qgis.org, dichiaro la mia preferenza
verso il marchio disegnato da salavatore la rosa.
il 3D attuale è bello ma non utile.

:-)

2017-10-13 9:58 GMT+02:00 Salvatore <notifications@github.com>:

**Comment by pigreco** [comment]
@aborruso 
> Ma prima di scegliere vuoi proporre nei vari spazi web di inviare altre idee qui? Tenere aperta la cosa per due settimane?

SI, per entrambe le domande.
Ma la prima NON posso decidere da solo!!!
