### ISSUE TITLE
Sondaggio nuovo logo

### ISSUE THREAD

**Issue by pigreco** [pigreco/logo_QGIS_3ITA#4]
@slarosa @ghtmtt @skampus @aborruso  @pyarchinit

ho creato in GDrive un **sondaggio test** - è solo una prova per definire le domande e tutto il resto.

[Cartella condivisa su GDrive](https://drive.google.com/drive/folders/0B9Mgi1GbTLXVVWREZnZRQ053Mms?usp=sharing) con immagini usate per il sondaggio

[Anteprima sondaggio](https://docs.google.com/forms/d/e/1FAIpQLSfATZsCO15Pfm_3YESmwLCzPoMjFV-djDTSTgTmeNgdAOOO4A/viewform)

**Comment by skampus** [comment]
Ottimo.
A chi pensi di estendere il sondaggio?

Nel gruppo chiuso siamo poche decine. Se ti ricordi Paolo pensava di
considerare come comunità attiva quelli che avendo dato il contributo
potevano votare come comunità italiana.
Questo se non ricordo male o, peggio, capito male.

Il gruppo pubblico invece è più numeroso.
Poi recupero i numeri

Il 10/Ott/2017 21:48, "Salvatore" <notifications@github.com> ha scritto:

**Comment by pigreco** [comment]
@skampus  bella domanda!!!
nel gruppo pubblico siamo meno di 300 (282) ma attivi pochissimi meno di 20.
nel gruppo chiuso ricordo 70 ma non sono sicuro, attivi 4/5

Personalmente estenderei a tutti il sondaggio con potere decisionale lasciato ai gruppi.
Potrei somministrare il sondaggio in vari social (il Gruppo FB GIS Italia ci sono circa 3000 membri) la pagina QGIS Italia è seguita da oltre 1500 persone.

Le mie sono solo idee e mi rimetto alla volontà del gruppo.  

EDIT: nel gruppo chiuso siamo solo in 28!!!

**Comment by pigreco** [comment]
@slarosa 
come procediamo?
[qui](https://github.com/pigreco/logo_QGIS_3ITA/wiki/Proposte) tutte le proposte pervenute.

usiamo gdrive per il sondaggio? oppure cosa consigli?

**Comment by skampus** [comment]
Scusa Totò ma non c'era la proposta anche del tricolore inscritto nella Q
non in 3D cioè senza ombreggiatura?

Il 20/Ott/2017 12:17, "Salvatore Fiandaca" <notifications@github.com> ha
scritto:

**Comment by pigreco** [comment]
@skampus 
come spiegato nel [wiki](https://github.com/pigreco/logo_QGIS_3ITA/wiki), una eventuale bandiera NON si presterebbe bene alle tre configurazioni: black, gree e white

![image](https://user-images.githubusercontent.com/7631137/31819075-468c9c2e-b59b-11e7-9003-f1661fdff01e.png)

poi, non so!!!
Fatemi sapere che fare....
io mi fermo e aspetto !!! ;-)

**Comment by skampus** [comment]
Ti chiedo scusa.
Me lo avevo già spiegato...
Hai ragione

Il 20/Ott/2017 13:37, "Salvatore Fiandaca" <notifications@github.com> ha
scritto:

**Comment by slarosa** [comment]
@pigreco per il sondaggio a mio avviso si dovrebbe utilizzare gdrive, stavo cercando di capire se è possibile utilizzare la piattaforma [loomio](https://www.loomio.org), ma non sono riuscito a fare una cosa carina.

**una nota a margine:** Nella sezione proposte del wiki, laddove si utilizza del testo nel logo, ho notato che c'è un font (per esempio per quello che ho proposto io la scritta ITA) strano e un po bruttino. Le specifiche parlano di [Trueno](https://smartfonts.com/trueno.font), pensi possiamo sistemarli prima del sondaggio?

**Comment by pigreco** [comment]
@slarosa mi sono permesso di modificare il tuo logo utilizzando il font trueno bold [vedi](https://github.com/pigreco/logo_QGIS_3ITA/wiki/Proposte) e [vedi](https://github.com/pigreco/logo_QGIS_3ITA/tree/master/proposte/slarosa).

Ho gia sistemato tutto e creato un sondaggio si [gdrive](https://docs.google.com/forms/d/e/1FAIpQLSfATZsCO15Pfm_3YESmwLCzPoMjFV-djDTSTgTmeNgdAOOO4A/viewform).

Alcune domande:

- **a chi somministrare il sondaggio?** quindi solo per votare e NON fare altre proposte!!
1. solo al gruppo chiuso (20 persone circa);
2. gruppo chiuso ed aperto (300 persone circa);
3. gruppo chiuso, aperto e vari social.

- **durata del sondaggio?**
- è opportuno scrivere una mail al gruppo chiuso in cui avvisiamo che la raccolta delle proposte è terminata e che faremo un sondaggio da somministrare a... (vedi punto precedente) e che il sondaggio inizierà in data x e terminerà in data y?

Io non vorrei aver perso tutto questo tempo per poi sentirmi dire da qualcuno che i loghi non si cambiano!!!

**Comment by slarosa** [comment]
Totò, tu ti puoi permettere tutto :-). Vedo il carattere come nello screenshot allegato, per questo ho chiesto.
<img width="324" alt="schermata 2017-10-20 alle 18 51 33" src="https://user-images.githubusercontent.com/1374682/31832611-ec4a394c-b5c7-11e7-8d0c-87efd807c23c.png">

> a chi somministrare il sondaggio? 
1. al gruppo aperto
2. un messaggio dalla pagina FB QGIS Italia (non so chi la amministra)

> durata del sondaggio?

non più di una settimana, solo un mio parere.

> è opportuno scrivere una mail al gruppo chiuso...

si dai, mi sembra corretto, farò lo stesso per il sondaggio appena chiuso relativo all'organizzazione.

> Io non vorrei aver perso tutto questo tempo per poi sentirmi dire da qualcuno che i loghi non si cambiano!!!

@pigreco hai fatto un lavoro eccellente, per questo ti ringrazio personalmente per tutti gli sforzi fatti per avviare e completare questo processo, grazie!
Non vedo motivazioni forti per cui il logo non debba essere cambiato, il processo è stato aperto a tutti in maniera democratica, se qualcuno aveva qualche motivo per non effettuare la modifica lo avrebbe già detto immagino.

**Comment by pigreco** [comment]
strano, io vedo cosi:
![image](https://user-images.githubusercontent.com/7631137/31835052-73848fc2-b5d0-11e7-9029-b9ab3969ca63.png)


**Allora procederò cosi:**
scrivo mail  al gruppo chiuso e aperto invitandoli a votare; `durata sondaggio una settimana`.
Userò gdrive per il sondaggio.
Poi, un post sulla pagina di Facebook (che ho l'onore e l'onere di co-amministrare con `Luca Mandolesi`, `Matteo Ghetta` e `Paolo Cavallini)` dove invito a iscriversi in `ML aperta` per partecipare al sondaggio.

**Comment by pigreco** [comment]
Sulla pagina FB vorrei fare cosi:

![image](https://user-images.githubusercontent.com/7631137/31839792-eca1967c-b5e2-11e7-9011-4f179b1f7e5e.png)

 è una bozza e pubblicherò a nome di QGIS Italia

**Comment by pigreco** [comment]
Ho fatto tutto,
ho scritto alle due ML e su Facebook.

Speriamo bene!!!

W QGIS!!!

CHIUDO issue!!!

**Comment by skampus** [comment]
Ho già risposto al sondaggio.grande Totò

Il 20/Ott/2017 22:25, "Salvatore Fiandaca" <notifications@github.com> ha
scritto:

**Comment by aborruso** [comment]
Grazie Totò

**Comment by skampus** [comment]
Chi ha vinto?

Il 22/Ott/2017 13:40, "Salvatore Fiandaca" <notifications@github.com> ha
scritto:

**Comment by pigreco** [comment]
@skampus 
> Chi ha vinto?

ancora è presto.
il sondaggio termina venerdi 27 alle 12:00
