### ISSUE TITLE
come procedere per la scelta del nuovo logo?

### ISSUE THREAD

**Issue by pigreco** [pigreco/logo_QGIS_3ITA#5]
Sposto qui la discussione su come procedere, la issue #2 sta diventando illeggibile.

Sembra unanime l'idea di aspettare ancora, ma aspettare cosa? In questo contenitore siamo solo in 4/5 nonostante abbia condiviso il link nella Lista del __gruppo chiuso__ (questo mi fa pensare che non è di grande interesse il logo di **QGIS Italia**, almeno in quel gruppo).

**Propongo di fare un passo alla volta:**
primo passo, dove condividere questo repo per ricevere altre idee sul logo:

1. nella lista __QGIS-it-user__  (lista aperta) chiedendo di collaborare?
2. nei vari social?
3. oppure decidiamo solo noi, quattro amici al bar?

**Comment by slarosa** [comment]
E' importante che il processo venga avviato subito, altrimenti rimaniamo fossilizzati in questa repo :-)

@pigreco io direi che possiamo procedere così:
* fare una chiamata anche sulla lista **QGIS-it-user** (_sul gruppo lo hai già fatto_), invitando a fare una proposta ed a visionare/valutare quelle già fatte;
* stessa chiamata sui social (_twitter, facebook, etc_);
* tenere aperta la chiamata per un paio di settimane, anche meno, io direi 10 giorni;
* infine procedere alla sostituzione del logo scelto ed alla condivisione dello stesso attraverso il plugin Resource sharing.

## _**Sono disponibile ad aiutare in questo processo!**_

**Comment by slarosa** [comment]
Nella chiamata, magari, sottolinea il fatto che il gruppo utenti italiani vuole arrivare ad una scelta condivisa e partecipata del nuovo logo per rendere il processo il più trasparente possibile in modo che tutti possano contribuire alla scelta del logo stesso.

**Comment by pigreco** [comment]
> fare una chiamata anche sulla lista QGIS-it-user (sul gruppo lo hai già fatto), invitando a fare una proposta ed a visionare/valutare quelle già fatte;

esempio chiamata sul gruppo aperto:

oggetto: **QGIS un nuovo logo QGIS Italia**

Ciao a tutti,
Qualche mese fa abbiamo cambiato il logo di **QGIS Italia** per adeguarlo al nuovo logo di QGIS 3.x di prossima uscita (nov/dic 2017).

il Gruppo degli Utenti italiani di QGIS (http://qgis.it/) vuole arrivare ad una scelta condivisa e partecipata del nuovo logo per rendere il processo il più trasparente possibile in modo che tutti possano contribuire alla scelta del logo stesso; quindi vi invito a leggere questo repo [0] in tutte le sue parti (issue, wiki).

Siete tutti invitati a fare una proposta ed a visionare/valutare quelle già fatte.

Per le proposte inviate un link alla risorsa zippata, per consigli e/o modifiche usate le issue!!!
Questa chiamata durerà non più di due settimane!!!

[0] https://github.com/pigreco/logo_QGIS_3ITA/wiki

--------------------
va bene? devo aggiungere altro?

**Comment by slarosa** [comment]
@pigreco secondo me va bene, l'unica cosa, farei riferimento solo al wiki per non distrarre/scoraggiare gli utenti. Il wiki, sistemato meglio per il caso, va più che bene.
(una volta fatto e prima di pubblicizzare, manda una mail al gruppo per favore)

Grazie Totò.

**Comment by pigreco** [comment]
@slarosa  appena puoi leggi il [wiki ](https://github.com/pigreco/logo_QGIS_3ITA/wiki)e le altre pagine,
cosi appena mi date il via scrivo email prima al gruppo chiuso e poi al quello aperto.

**Comment by slarosa** [comment]
Va benissimo, ho solo un dubbio :-(:
- il logo corona, sulla base di quanto spieghi sul wiki, andrebbe tolto, visto che non rispetta le specifiche, giusto? o dovremmo comunque considerarla una proposta non in linea con le specifiche?

In ogni caso, meglio proporre sul gruppo subito, almeno ci assicuriamo che tutti sappiano cosa si vuole fare :-)

**Comment by pigreco** [comment]
@slarosa @aborruso 
> il logo corona, sulla base di quanto spieghi sul wiki, andrebbe tolto, visto che non rispetta le specifiche, giusto?

hai ragione, con il permesso di Andy tolgo il logo corona, ecco un test:
![image](https://user-images.githubusercontent.com/7631137/31576069-fa2a0430-b0f3-11e7-97e3-48443934147a.png)

> In ogni caso, meglio proporre sul gruppo subito, almeno ci assicuriamo che tutti sappiano cosa si vuole fare :-)

alludi al gruppo chiuso?

**Comment by slarosa** [comment]
> alludi al gruppo chiuso?

Si!
Ma @aborruso è iscritto al gruppo?, mi sembra di capire di no! :-(

**Comment by pigreco** [comment]
> Ma @aborruso è iscritto al gruppo?, mi sembra di capire di no! :-(

No, @aborruso non è iscritto.
Al gruppo chiuso fanno parte SOLO 28 persone, almeno cosi ho visto!!!

Procedo subito a scrivere nel gruppo.

**Comment by aborruso** [comment]
Sì, grazie. Ribadisco che il mio logo non ha senso, purtroppo l'ho disegnato senza avere capito gli obiettivi.
