### ISSUE TITLE
Nuovo proposte da lista QGIS -it- user

### ISSUE THREAD

**Issue by pigreco** [pigreco/logo_QGIS_3ITA#7]
Marco Spaziani: (dalla lista scrive)
Per me ok per il logo matita ma direi, se possibile, IT invece di ITA ...credo che IT sia la sigla internazionale dell'Italia, per lo meno in ambito internet o delle targhe automobilistiche e quindi dovrebbe essere più facilmente interpretabile dagli amici fuori frontiera.

https://github.com/pigreco/logo_QGIS_3ITA/blob/master/proposte/spaziani/qgis-logo3_IT.svg

ho modificato il logo di @slarosa sostituendo ITA con IT, inoltre ho usato il font da specifica (Trueno Bold 24)

![image](https://user-images.githubusercontent.com/7631137/31633926-0e7c68b8-b2c2-11e7-98ca-28722f9138d1.png)

ho aggiornato le proposte!!!

**Comment by slarosa** [comment]
il font non lo avevo considerato, mi era sfuggito, bravo @pigreco  :-)
La sigla internazionale può essere a due o tre lettere [0], ad essere sincero io preferisco quella a tre lettere (alpha-3) che è pur sempre uno standard inequivocabile ;-)

[0] - https://it.wikipedia.org/wiki/ISO_3166-1

**Comment by pigreco** [comment]
Ottimo,
quante cose si imparano.
Sinceramente, anche a me piace alpha-3!!!

**Comment by pigreco** [comment]
Ivano wrote
Premesso che apprezzo molto le proposte fatte sino ad oggi, 
mi permetto però di condividere con voi un mio pensiero a riguardo. 

Sono del parere che il logo di Qgis rappresenti l'internazionalità di tutto 
l'ecosistema che vi gira intorno, in tutti in suoi aspetti, ritengo che la 
sua impronta originale non dovrebbe essere alterata, ma riconosciuta sempre 
come unico gruppo. 

Altra cosa invece è l'inquadramento del sottogruppo, nel nostro caso l' 
Italia, che ne rappresenta una appendice e come tale la si puo' manifestare 
all'interno del logo stesso, senza andare a modificare l'originalità di 
base. 

Le mie proposte sono molto semplici ed essenziali, minimal material design, 
mantenendo l'originalità ma al contempo inquadrando il sottogruppo di 
appartenenza, senza troppa enfasi. 

PropostaLogoQgis_1 
<https://github.com/ivanogiuliano/LogoQgis/blob/master/LogoSigla_.jpg>  

PropostaLogoQgis_2 
<https://github.com/ivanogiuliano/LogoQgis/blob/master/LogoFlag.JPG>  

Ivano

**Comment by pigreco** [comment]
Alessandro Sarretta
Ciao Totò,

intanto grazie per la condivisione. Non sono in grado (un po' per tempo, un po' per capacità) di preparare una proposta grafica ma, agganciandomi a quanto fin qui discusso provo ad elencare poche considerazioni:

- l'idea di inserire il codice ITA mi sembra il più semplice ed efficace. Propenderei per le 3 lettere (che è cmq anch'esso standard ISO: https://www.wikiwand.com/en/ISO_3166-1_alpha-3) perché più esplicito. Ogni tanto mi capita di vedere confusione, in ambito internazionale, con il codice IT che può essere confuso per Information Technology...

- cercherei di mantenere la forma quadrata del logo, e non aggiungere elementi grafici che lo rendano rettangolare

- si potrebbe pensare di aggiungere da qualche parte (background, al centro, lascio ai grafici la scelta) la forma dell'Italia (tipo https://image.flaticon.com/icons/png/512/24/24335.png). Siamo fortunati ad avere un territorio con una forma molto riconoscibile... potremmo sfruttarla

![image](https://user-images.githubusercontent.com/7631137/31764461-8922388a-b4c1-11e7-8c02-e59eb5587979.png)

oppure cosi:
![image](https://user-images.githubusercontent.com/7631137/31783403-6acaf34e-b4fe-11e7-86f1-fb2b1bbd67d4.png)
